### ISSUE TITLE
Bulk copy-paste work codes: Uncaught TypeError

### ISSUE THREAD

**Issue by doppelhelix** [ROpdebee/mb-userscripts#806]
If I press the "`Copy work codes`" button, this error shows up.
Pressing "`Fill work codes`" in musicbrainz shows `No data found. Did you copy anything?`

Tried with a fresh Firefox profile with Violentmonkey 2.30.0 as the only extension.
```
Uncaught TypeError: table.querySelector(...) is null
    findIswcs moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/ MB: Bulk copy-paste work codes.user.js#1:1036
    parseAndCopy moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/ MB: Bulk copy-paste work codes.user.js#1:1050
    onclick moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/ MB: Bulk copy-paste work codes.user.js#1:1067
    handleChangeCisac moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/ MB: Bulk copy-paste work codes.user.js#1:1067
    handleISWCNet moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/ MB: Bulk copy-paste work codes.user.js#1:1071
    VMh99fpfrhrp moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/ MB: Bulk copy-paste work codes.user.js#1:1156
    VMh99fpfrhrp moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/ MB: Bulk copy-paste work codes.user.js#1:1158
    rn moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/sandbox/injected-web.js:1
    <anonymous> moz-extension://03a6f851-a0d0-4cb1-a9a7-25566726ade8/ MB: Bulk copy-paste work codes.user.js#1:1

```

**Comment by dragonzeron** [comment]
Can also confirm this as an issue I thought it might have been with chrome but I do not know for sure.

**Comment by Lioncat6** [comment]
What sites does this occur on? The script supports multiple

**Comment by dragonzeron** [comment]
> What sites does this occur on? The script supports multiple

Musicbrainz and Iswcnet

**Comment by Lioncat6** [comment]
Oh wait, didn't see you replied lol

**Comment by Lioncat6** [comment]
Now that I've actually named my commits right (never used Semantic PR before...), this pull should fix it

https://github.com/ROpdebee/mb-userscripts/pull/808

**Comment by dragonzeron** [comment]
Ok I am gonna try it out and see what it can do

**Comment by dragonzeron** [comment]
Just tried using the temporary fix and its still not working like I am going on the iswcnet and doing the copy work codes and then when i try to paste it on musicbrainz nothing happens if you want i can try to screen record whats happening and it send it here

**Comment by dragonzeron** [comment]
> Now that I've actually named my commits right (never used Semantic PR before...), this pull should fix it
> 
> [#808](https://github.com/ROpdebee/mb-userscripts/pull/808)
> 
> If anyone really needs a working version, you can temporarily use this before it gets merged: https://github.com/Lioncat6/mb-userscripts/raw/refs/heads/patch-1/mb_bulk_copy_work_codes.user.js

Ok thank you the temp fix seemed to work appreciate it

**Comment by Lioncat6** [comment]
Np!

**Comment by kellnerd** [comment]
Should finally be fixed by today's update.
